### ISSUE TITLE
Build Error - Duplicate Routes 

### ISSUE THREAD

**Issue by spider-sauce** [saucelabs/elemental-next#100]
When running `npm run build` in the `frontend` directory, the following warnings are thrown:

```
9:38:01 AM: [WARNING] Duplicate routes found!
9:38:01 AM: - Attempting to create page at /docs/updated-tips/download-a-file/2-download-a-file, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/how-to-access-basic-auth/13-work-with-basic-auth, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/how-to-access-basic-auth/13-work-with-basic-auth, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/how-to-press-keyboard-keys/61-keyboard-keys, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/how-to-press-keyboard-keys/61-keyboard-keys, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/how-to-test-checkboxes/45-checkboxes, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/how-to-test-checkboxes/45-checkboxes, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/how-to-test-checkboxes/45-checkboxes, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/how-to-test-checkboxes/45-checkboxes, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/how-to-upload-a-file/1-upload-a-file, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/how-to-work-with-hovers/50-hovers, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/how-to-work-with-hovers/50-hovers, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/how-to-work-with-javascript-alerts/51-javascript-alerts, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/how-to-work-with-javascript-alerts/51-javascript-alerts, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/select-from-a-dropdown/5-select-from-a-dropdown, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/select-from-a-dropdown/5-select-from-a-dropdown, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/select-from-a-dropdown/5-select-from-a-dropdown, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/select-from-a-dropdown/5-select-from-a-dropdown, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/template/0-template, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/template/0-template, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/template/0-template, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/work-with-frames/3-work-with-frames, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/work-with-frames/3-work-with-frames, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/work-with-frames/3-work-with-frames, but a page already exists at this route.
9:38:01 AM: - Attempting to create page at /docs/updated-tips/work-with-frames/3-work-with-frames, but a page already exists at this route.
9:38:01 AM: This could lead to non-deterministic routing behavior.
9:38:01 AM: [info] [webpackbar] Compiling Client
9:38:01 AM: [info] [webpackbar] Compiling Server
9:38:36 AM: [success] [webpackbar] Client: Compiled successfully in 34.50s
9:38:41 AM: [ERROR] Docusaurus server-side rendering could not render static page with path /docs/non-updated-tips/oop/37-oop.
9:38:42 AM: [ERROR] Docusaurus server-side rendering could not render static page with path /docs/non-updated-tips/web-consistency-testing/62-web-consistency-testing.
9:38:44 AM: [success] [webpackbar] Server: Compiled with some errors in 42.63s
9:38:44 AM: Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
9:38:44 AM: Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
9:38:44 AM: [ERROR] Unable to build website for locale en.
9:38:44 AM: [ERROR] Error: Failed to compile with errors.
9:38:44 AM:     at /opt/build/repo/frontend/node_modules/@docusaurus/core/lib/webpack/utils.js:180:24
9:38:44 AM:     at /opt/build/repo/frontend/node_modules/webpack/lib/MultiCompiler.js:554:14
9:38:44 AM:     at processQueueWorker (/opt/build/repo/frontend/node_modules/webpack/lib/MultiCompiler.js:491:6)
9:38:44 AM:     at processTicksAndRejections (node:internal/process/task_queues:78:11)
9:38:44 AM: [INFO] Docusaurus version: 2.3.1
9:38:44 AM: Node version: v16.19.1
9:38:44 AM: ​
9:38:44 AM:   "build.command" failed                                        
9:38:44 AM: ────────────────────────────────────────────────────────────────
9:38:44 AM: ​
9:38:44 AM:   Error message
9:38:44 AM:   Command failed with exit code 1: npm run build (https://ntl.fyi/exit-code-1)
9:38:44 AM: ​
9:38:44 AM:   Error location
9:38:44 AM:   In Build command from Netlify app:
9:38:44 AM:   npm run build
9:38:44 AM: ​
9:38:44 AM:   Resolved config
9:38:44 AM:   build:
9:38:44 AM:     base: /opt/build/repo/frontend
9:38:44 AM:     command: npm run build
9:38:44 AM:     commandOrigin: ui
9:38:44 AM:     environment:
9:38:44 AM:       - NO_INDEX
9:38:44 AM:       - TARGET_URL
9:38:44 AM:     publish: /opt/build/repo/frontend
9:38:44 AM:     publishOrigin: default
9:38:45 AM: Caching artifacts
9:38:45 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
```

Resolves #103

**Comment by aquaomarine** [comment]
[The doc's slug front matter customizes the last part of the route](https://docusaurus.io/docs/advanced/routing) So I'm thinking the slug needs to be 3-work-with-frames-ruby, specifying the specific language so it's not the same. 

I've done it for one tip and it's no longer duplicating.

**Comment by spider-sauce** [comment]
@aquaomarine yep, every slug needs to be unique. Not sure if it would be easier to have one page per tip and just toggle languages in code examples using tabs: https://docusaurus.io/docs/markdown-features/tabs

We may have to rewrite the content, but it would make managing the pages less of a headache

**Comment by aquaomarine** [comment]
Yeah this aligns more with Djangos design, and I think eventually we'll be heading that way but then we'll be scraping all the docs. Which should still be fine.

**Comment by diemol** [comment]
I think this should be reworked because the current structure shows several files inside a directory for each tip, with almost the same content but different code.

We should revisit and consolidate the content, then use the [Tabs](https://docusaurus.io/docs/markdown-features/tabs) feature in Docusaurus to show the code.

**Comment by spider-sauce** [comment]
Hey all, I'm reopning this issue. Still getting the duplicate routes warning which is causing server-side rendering issue again:

```
[WARNING] Duplicate routes found!
- Attempting to create page at /docs/python, but a page already exists at this route.
This could lead to non-deterministic routing behavior.

✔ Client
  

✖ Server
  Compiled with some errors in 42.87s

[ERROR] Docusaurus server-side rendering could not render static page with path /docs/non-updated-tips/oop/37-oop.


Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
[ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
    at /Users/jamestacker/Documents/saucelabs/elemental-next/frontend/node_modules/@docusaurus/core/lib/webpack/utils.js:180:24
    at /Users/jamestacker/Documents/saucelabs/elemental-next/frontend/node_modules/webpack/lib/MultiCompiler.js:554:14
    at processQueueWorker (/Users/jamestacker/Documents/saucelabs/elemental-next/frontend/node_modules/webpack/lib/MultiCompiler.js:491:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

**Comment by discombobulateme** [comment]
@aquaomarine can you take a look at this, please? :)
